const amenityPhrases = [
    "garden",
    "house keeping",
    "air conditioner",
    "waste treatment plant",
    "battery back up",
    "elevator",
    "wifi",
    "swimming pool",
    "furnished",
    "gym",
    "car parking",
    "parking space",
    "near to metro and airport",
    "power backup",
    "security",
    "pet friendly",
    "parking",
    "drinking water",
    "air conditioning",
    "luggage storage",
    "near to metro station",
    "In-unit Laundry",
    "Air conditioning",
    "Storage Space or Large Closets",
    "Patio or Balcony Space",
    "Dishwasher",
    "Energy-efficient Appliances",
    "High-speed Internet Access",
    "Large Windows with Natural Light",
    "Views",
    "Fireplace",
    "Hardwood Floors",

    "Laundry Facilities",
    "Laundry Services",
    "Package Lockers",
    "Gated Community",
    "Security Guards/Doormen",
    "Community Events/Classes",
    "Extra Storage Space",

    "Secured Garage",
    "Assigned Parking Spaces, Carport, Covered Parking Spaces",
    "Access to Public Transportation",
    "Electric Vehicle Charging Stations",
    "Guest Parking",

    "Pet-friendly Units",

    "Swimming Pool",
    "Barbecue Areas",
    "Firepits",
    "Gym/Fitness Centers",
    "Yoga/Cardio Rooms",
    "Community Clubhouse",
    "Playground",
    "Rooftop Lounge Areas",
    "Community Garden",
    "Media Rooms",
    "Church/Mosque/Temple/prayer hall ",
    "Common Areas",
  ];

  export default amenityPhrases;